### ISSUE TITLE
SQLite image is not working

### ISSUE THREAD

**Issue by chihkaiyu** [droher/boxball#31]
Hi,
I found that sqlite image is not working when I follow the usage in README which is 
`docker run --name sqlite -d -p 8080:8080 -v ~/boxball/sqlite:/db doublewick/boxball:sqlite-0.0.2`

The container will exit immediately and the error message shows:
```
$ docker logs sqlite 
zstd: can't stat /db/boxball.db.zst : No such file or directory -- ignored
```

I try not to mount the data folder and there is another problem. The container won't print any message and becomes to exited after a while. The weird thing is that the container will still be displayed if you use `docker ps` to show status.
```
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED              STATUS              PORTS                               NAMES
8618c27cc60c        doublewick/boxball:sqlite-0.0.2   "/bin/sh -c 'zstd --…"   About a minute ago   Up About a minute   0.0.0.0:8080->8080/tcp              sqlite
```

But it's actually exited if you use `docker inspect sqlite` to display the status:
```
$ docker inspect sqlite
[
    {
        "Id": "8618c27cc60c2d227977a29ba7942b5d63e22daa227a376b079858523a9345ea",
        "Created": "2019-06-14T05:41:52.886829683Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "zstd --rm -d /db/boxball.db.zst && sqlite_web -H 0.0.0.0 -x /db/boxball.db"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 73,
            "Error": "",
            "StartedAt": "2019-06-14T05:41:53.700159123Z",
            "FinishedAt": "2019-06-14T05:42:23.108049305Z"
        },
```

I have no idea why this is happening and I'll guess it's because the data is too large.

**Comment by droher** [comment]
Thanks for pointing this out, @chihkaiyu. I just pushed the wrong version to Docker Hub. I'm uploading a new one now and it should be up in about an hour (I'll post again when it's complete).

**Comment by droher** [comment]
Ok, the new image is up. It's working for me so I am closing the issue, but please reopen if you are still having problems. Thanks again!
