### ISSUE TITLE
Add Gameday Data

### ISSUE THREAD

**Issue by droher** [droher/boxball#39]

**Comment by albertlyu** [comment]
Are you planning to add Gameday data via MLBAM's traditional XML feeds? Or their Stats API?

**Comment by droher** [comment]
I was probably going to use the GitHub packages that have already been
developed for that purpose. Would rather reuse code and consolidate good
existing solutions in the community.

**Comment by droher** [comment]
I've decided not to add any more data and instead focus on data integration in a different, yet-to-be-released project.
