### ISSUE TITLE
retrosheet_event table empty for postgres-cstore-fdw

### ISSUE THREAD

**Issue by BBergquist** [droher/boxball#59]
Executing `SELECT COUNT(*) FROM retrosheet_event;` returns 0. I've tried the latest image and 2020.2.

**To Reproduce**
1. `docker run --name postgres-cstore-fdw -d -p 5433:5432 -e POSTGRES_PASSWORD="postgres" -v ~/boxball/postgres-cstore-fdw:/var/lib/postgresql/data doublewick/boxball:postgres-cstore-fdw-latest`
2. `psql -U postgres -p 5433`
3. `SELECT COUNT(*) FROM retrosheet_event`
4. Output should be zero.

**Expected behavior**
Is the event data still being included in the images?

**Desktop (please complete the following information):**
 - OS: Windows 10 w/ WSL 2-based docker
 - Version: doublewick/boxball:postgres-cstore-fdw-latest

**Comment by droher** [comment]
I'm unable to reproduce this error. Could you try removing the volume/container and trying again? The event table loads last and takes the longest, so it's possible that it got interrupted.
```
docker rm -f postgres-cstore-fdw
rm -rf ~/boxball/postgres-cstore-fdw
```
If you're still getting it after that, could you post the container logs?

**Comment by BBergquist** [comment]
Thank you, I will try that. It might be a week or so until I am able to follow up.

**Comment by BBergquist** [comment]
You are correct. I must have messed it up the first time. Thank you for the quick help!
