### ISSUE TITLE
Update with 2022 season from Retrosheet

### ISSUE THREAD

**Issue by double-dose-larry** [droher/boxball#66]
Retrosheet recently published the 2022 season (among other corrections/changes)

https://www.retrosheet.org/Fall2022Release.html

I was wondering if you could update to include the new data.

Please and thank you!

**Comment by droher** [comment]
Currently working on it! I found a few bugs in the data that are preventing boxball's build process from succeeding, and the folks over at Retrosheet are working to correct them. 

(If you're interested, the email list is open to anyone to join and the posts are public here: https://groups.io/g/RetroList/topics)

**Comment by droher** [comment]
Images are updated!

**Comment by sdvinay** [comment]
Awesome, thank you so much for all of you work on this project!

Any chance you can publish updated parquet files as well?  Thanks!

**Comment by droher** [comment]
Thanks for the reminder - just added them.
