### ISSUE TITLE
Update data to the Summer 2023 Release

### ISSUE THREAD

**Issue by double-dose-larry** [droher/boxball#68]
Hi,

Tom Thress recently announced the availability of the first semi-annual Summer 2023 Release.

https://www.retrosheet.org/june2023release.html

I was wondering if boxball can be updated to reflect the changes. Mainly, I'm interested in the new optional field,  `gametype`, that's now included. It's been a real sore point for me to figure out based on game dates and what not.

```
A new info record type was introduced in 2023 describing the type of game.

info,gametype,regular

The possible types are:
regular
exhibition
preseason
allstar
playoff
worldseries
lcs
divisionseries
wildcard
championship
```

Thank you so much for putting this project together.

**Comment by droher** [comment]
Boxball relies on the Chadwick Bureau's retrosheet repo, which hasn't updated yet: https://github.com/chadwickbureau/retrosheet

I'll keep tabs on that and should be able to update soon after. However, you may end up being disappointed in the result, because new info fields in the raw data don't automatically end up in Chadwick's data outputs.

**Comment by double-dose-larry** [comment]
Dang it! I was so excited when I saw that. I'll go open an issue there and see if goes anywhere.

Well, in any case, thank you again for your efforts!

**Comment by droher** [comment]
I'm working on a project which will serve as the successor to Boxball (which will still be maintained) - here is a list of game IDs along with their game types. More to come, hope this is useful in the interim! 
[game_types.csv](https://github.com/droher/boxball/files/11984000/game_types.csv)

**Comment by double-dose-larry** [comment]
dude...


you're the man. this is great
