### ISSUE TITLE
Missing Retrosheet player data

### ISSUE THREAD

**Issue by smcpeck** [droher/boxball#69]
**Describe the bug**
When analyzing RetroSheet data, there is no way to join to player information.

**Additional context**
Retrosheet offers a `biofile.csv` data source that does not come in from the upstream Chadwick repository. This data would be super helpful to have as a table within the `retrosheet` schema.

Reference: https://www.retrosheet.org/biofile.htm

**Comment by droher** [comment]
What about the `People` table in the baseball databank schema? It has a retroid field.

**Comment by smcpeck** [comment]
Ahhh! Perfect. I missed that column and was trying to join directly to `player_id`.

Many thanks!
