### ISSUE TITLE
Row-based Postgres not populating

### ISSUE THREAD

**Issue by ericlesslie** [droher/boxball#77]
**Describe the bug**
Waited well over 90 minutes for the population of the row-based postgres docker image, and it seems like the data isn't populating in the postgres database. The data seems to exist in the boxball directory, but it's not showing when I try to access it in the database. 

I installed the sqlite image to see if it was all the images, but it worked as expected, so it might just be that particular image that has a problem

**To Reproduce**
1. Follow instructions to start up row-based postgres docker image
2. Leave up for 6 hours, and the data is not populated

**Expected behavior**
Data should populate in around 90 minutes

**Screenshots**
![image](https://github.com/droher/boxball/assets/55772858/c732d542-588b-4a8f-b669-4df754f24226)

![image](https://github.com/droher/boxball/assets/55772858/c8143755-5af5-4983-b2e2-08912f1632d8)

**Desktop:**
 - OS: Fedora 39 (Workstation) x86_64
 - Kernel: 6.5.9-300.fc39.x86_64
 - Docker: 24.0.7

**Comment by ericlesslie** [comment]
I have fixed it, it was on my end.

**Comment by droher** [comment]
What was the fix, in case others have a similar problem?

**Comment by ericlesslie** [comment]
I didn't check the schema list with ```\dn```

![image](https://github.com/droher/boxball/assets/55772858/13121189-5f53-418a-a638-0aa97d37041e)

I'm a student and new to postgres and thought that \dt would list all tables in the connected database in postgres. It only lists tables in public schemas, which is why I thought it was not populating.

![Screenshot from 2023-12-09 15-16-17](https://github.com/droher/boxball/assets/55772858/f5a1eb57-b701-4822-9307-fac3e4e5cb97)

This could've been discovered with a [StackOverflow post](https://stackoverflow.com/questions/34098326/how-to-select-a-schema-in-postgres-when-using-psql), but instead I rush to make an issue. 🤦
